#!/usr/bin/env python3
"""Offline, repo-local documentation projection and pinned source parity (MIT)."""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path


def digest(data):
    return hashlib.sha256(data).hexdigest()


def local(root, name):
    path = Path(name)
    if path.is_absolute() or ".." in path.parts or not path.parts:
        raise ValueError("unsafe repository path: " + name)
    result = root / path
    if root.resolve() not in (result.resolve(), *result.resolve().parents):
        raise ValueError("path escapes repository: " + name)
    return result


def render(root, config):
    lines = ["# Repository source map", "", "Generated by repository_docs.py; edit the source files and regenerate.",
             "This is source evidence, not deployment or operational certification.", "",
             "Repository: `" + config["repository"] + "`", "", "## Source-owned entry points", ""]
    for entry in config["entrypoints"]:
        path = local(root, entry)
        if not path.is_file():
            raise ValueError("missing entry point: " + entry)
        lines.append("- `" + entry + "`")
    lines += ["", "## Manifest and workflow fingerprints", "",
              "A changed fingerprint requires review of its related documentation; it does not prove prose is accurate.", ""]
    for item in config["sources"]:
        name = item["path"]
        data = local(root, name).read_bytes()
        lines += ["- `" + name + "` — " + item["purpose"] + " (SHA-256 `" + digest(data) + "`)"]
        if name.endswith("package.json"):
            manifest = json.loads(data)
            for field in ("packageManager", "engines", "scripts", "dependencies", "devDependencies"):
                if field in manifest:
                    lines += ["", "### `" + name + "`: " + field, "", "```json", json.dumps(manifest[field], indent=2, sort_keys=True), "```", ""]
    lines += ["", "## Pinned shared sources", "", "Updates are independent reviewable consumer changes. Local instructions remain source-owned.", ""]
    for item in config["imports"]:
        lines.append("- `" + item["destination"] + "` ← `" + item["repository"] + "@" + item["revision"] + ":" + item["path"] + "` (SHA-256 `" + item["sha256"] + "`)")
    return ("\n".join(lines) + "\n").encode()


def run(root, write=False, upstreams=None):
    root = Path(root).resolve()
    config = json.loads((root / "repository-docs.json").read_text())
    if config["schemaVersion"] != 1 or not config["sources"] or not config["entrypoints"]:
        raise ValueError("invalid documentation registry")
    upstreams = upstreams or {}
    pending, errors, destinations = [], [], set()
    # Validate every import before writing anything; never run upstream code.
    for item in config["imports"]:
        target = local(root, item["destination"])
        if target in destinations or target == local(root, config["output"]) or target == root / "repository-docs.json":
            raise ValueError("duplicate or reserved import destination")
        destinations.add(target)
        if not re.fullmatch(r"[0-9a-f]{40}", item["revision"]) or not re.fullmatch(r"[0-9a-f]{64}", item["sha256"]):
            raise ValueError("imports require immutable revision and SHA-256")
        # Validate the Git source path separately from the destination.
        local(root, item["path"])
        source = upstreams.get(item["repository"])
        if source:
            data = subprocess.run(["git", "-C", str(source), "show", item["revision"] + ":" + item["path"]], check=True, capture_output=True).stdout
            if digest(data) != item["sha256"]:
                raise ValueError("upstream content does not match pin: " + item["destination"])
            if write:
                pending.append((target, data))
            elif not target.is_file() or target.read_bytes() != data:
                errors.append("shared source drift: " + item["destination"])
        elif not target.is_file() or digest(target.read_bytes()) != item["sha256"]:
            errors.append("pinned copy missing or changed: " + item["destination"])
    output = local(root, config["output"])
    if output == root / "repository-docs.json" or output in {local(root, i["path"]) for i in config["sources"]}:
        raise ValueError("projection cannot overwrite a source")
    projection = render(root, config)
    if errors:
        return errors
    if write:
        for target, data in pending + [(output, projection)]:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
    elif not output.is_file() or output.read_bytes() != projection:
        errors.append("source projection stale: " + config["output"])
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--upstream", action="append", default=[], metavar="OWNER/REPO=CHECKOUT")
    args = parser.parse_args()
    try:
        errors = run(args.root, args.write, dict(item.split("=", 1) for item in args.upstream))
    except (ValueError, KeyError, TypeError, OSError, subprocess.CalledProcessError) as exc:
        parser.exit(1, "repository-docs: " + str(exc) + "\n")
    for error in errors:
        print("repository-docs: " + error)
    if errors:
        return 1
    print("repository-docs: source parity verified (no runtime claim)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
